# Generated by Django 4.2.5 on 2023-10-22 04:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wb", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="media",
            unique_together={("series", "season", "episode_number")},
        ),
    ]
