# Generated by Django 4.2.5 on 2023-10-27 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wb", "0002_alter_media_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchparty",
            name="media",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watch_parties",
                to="wb.media",
            ),
            preserve_default=False,
        ),
    ]
