# Generated by Django 4.2.5 on 2023-10-31 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wb", "0003_watchparty_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchedlist",
            name="media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watches",
                to="wb.media",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="watchedlist",
            unique_together={("user", "media")},
        ),
    ]
