name: CI

on: [push]

env:
  SECRET_KEY: ci_testing
  DEBUG: True

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Check Django setup
        working-directory: src/
        run: python3 manage.py check

      - name: Run Tests
        working-directory: src/
        run: pytest -v